---

- name: Create Nagios user
  user: name={{ USER }} comment="{{ USER }} User" 
  ignore_errors: yes

- name: Create user .ssh directory 
  command: mkdir /home/{{ USER }}/.ssh

- name: Copy authorized keys
  copy: src=nagios-key dest=/home/{{ USER }}/.ssh/authorized_keys mode=0644

- name: Set home directory permissions 
  command: chown -R {{ USER }}:{{ USER }} /home/{{ USER }}