---

- name: Copy nagios plugins
  copy: src=show_users dest=/home/{{ USER }}/bin
  
- name: Confirm plugin file permissions 
  shell: chmod 777 /home/nagios/bin/*

- name: Confirm plug file ownership 
  shell: chown -R nagios:nagios /home/nagios/bin